sudo: required
dist: trusty
language: python
cache:
    - apt
    - pip

python:
  - 3.5
  - 3.6

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get update
  - sudo apt-get install geoipupdate
  - echo 'UserId 999999' | sudo tee /etc/GeoIP.conf > /dev/null
  - echo 'LicenseKey 000000000000' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - echo 'ProductIds GeoLite2-Country GeoLite2-City GeoLite2-ASN' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - sudo geoipupdate -v
  - sudo apt-get install shellcheck

install:
  - pip install pip --upgrade
  - easy_install distribute
  - pip install setuptools --upgrade
  - pip install -r dev_requirements.txt

script:
  - python setup.py test
  - python setup.py sdist bdist bdist_wheel
  - shellcheck -x deploymentkit/easybutton.sh
  - shellcheck -x deploymentkit/ubuntu16/bootstrap.sh

notifications:
  email:
    on_success: never
    on_failure: never

